### ISSUE TITLE
Please add something to the readme.md file as this is the first thing visitors see

### ISSUE THREAD

**Issue by scharlau** [AbdnCHDS/covid-social-distancing#14]
The readme.md file should explain the outline of the repository, how people use it, test it, and contribute, and expected outcomes. etc. By all means point them to other pages, but do put something here.

**Comment by will-ball** [comment]
I'm happy to write a short piece in the README, pointing people towards the code of conduct & contributing files, as well as giving an overview of the project as it stands.

Any other suggested content to go in there just now @dblana @BScheliga ?

**Comment by BScheliga** [comment]
The centres webpage?

**Comment by dblana** [comment]
Thanks Will, that would be great! You can start a branch for this if you'd like to practice 😄

**Comment by will-ball** [comment]
Was the merge supposed to close this issue or did I do something wrong @dblana ?

**Comment by dblana** [comment]
Ah! So I had a look at the [pull request](https://github.com/AbdnCHDS/covid-social-distancing/pull/15) and you said: Closes #15 - but #15 is the number of the pull request itself, not the issue. It should say: Closes #14
No worries, just close this issue manually 😃
