### ISSUE TITLE
Add coding and code reviewing guidelines

### ISSUE THREAD

**Issue by BScheliga** [AbdnCHDS/covid-social-distancing#7]
This is a document that explains how to roughly structure and comment your comment. As well as how to review the code of others.

**Comment by BScheliga** [comment]
@dblana or do you think we should out put this rather into the guidebook?

**Comment by dblana** [comment]
Yes, I think that anything that is useful beyond a particular project should be in the guidebook. You could argue that in that case the contributing guidelines could be in the guidebook too, but I'm thinking we might customize these a bit to each project. And they are specific to github, while writing good code is a more general skill... What do you think?

**Comment by BScheliga** [comment]
@dblana I believe the guidebook is the right place avoid repetition. And could the place for copy & paste standard text on contribution guideline etc.

**Comment by dblana** [comment]
So... will you open an issue on the guidebook repo about code guidelines? You don't need to assign it to yourself 😆 
I need to update the contributing guidelines for the guidebook, I talk about forking but I think this collaborative development model (with everyone having "write" access but working in different branches as we do here) is better.

**Comment by BScheliga** [comment]
I have opened a new issue in the guidebook [Issue 11](https://github.com/AbdnCHDS/guidebook/issues/11l)
